version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-node-app  # Change this to your desired path

hooks:
  BeforeInstall:
    - location: |
        #!/bin/bash
        echo "Stopping existing container..."
        docker stop my-node-app || true
        docker rm my-node-app || true

  AfterInstall:
    - location: |
        #!/bin/bash
        REGION="ap-south-1"  # AWS region
        ACCOUNT_ID="654654277756"  # Your AWS account ID
        REPOSITORY_NAME="node-repo"  # ECR repository name
        IMAGE_TAG="latest"  # Tag of the image you want to pull

        echo "Authenticating Docker to ECR..."
        aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

        echo "Pulling Docker image from ECR..."
        docker pull $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME/nodeimage:$IMAGE_TAG

        echo "Running Docker container..."
        docker run -d --name my-node-app -p 3000:3000 $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME/nodeimage:$IMAGE_TAG

  ApplicationStart:
    - location: |
        #!/bin/bash
        echo "Starting the application..."
        docker start my-node-app || true

  Validate
